### ISSUE TITLE
"Agent Study" not showing

### ISSUE THREAD

**Issue by Ashargin** [mjothy/grid2viz#18]
Grid2viz fails to switch from the "Agent Overview" page to the "Agent Study" page.

This occurs with the following traceback:
```
Traceback (most recent call last):
  File "D:\Anaconda3\Lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Anaconda3\Lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Anaconda3\Lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Anaconda3\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Anaconda3\Lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Anaconda3\Lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Anaconda3\Lib\site-packages\dash\dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "D:\Anaconda3\Lib\site-packages\dash\dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
File "D:\Anaconda3\Lib\site-packages\Grid2Viz\grid2viz\app.py", line 150, in register_page_lyt
    return micro.layout(user_selected_timestamp, study_agent, ref_agent, scenario), "micro"
  File "D:\Anaconda3\Lib\site-packages\Grid2Viz\grid2viz\src\micro\micro_lyt.py", line 247, in layout
    network_graph = make_network(new_episode).get_plot_observation(new_episode.observations[center_indx])
  File "D:\Anaconda3\Lib\site-packages\Grid2Viz\grid2viz\src\manager.py", line 26, in make_network
    substation_layout=network_layout, observation_space=episode.observation_space)
  File "d:\scripts_python\grid2op\grid2op\Plot\PlotPlotly.py", line 239, in __init__
    bus_radius=bus_radius)
  File "d:\scripts_python\grid2op\grid2op\Plot\BasePlot.py", line 64, in __init__
    "Your layout is invalid".format(len(substation_layout), observation_space.n_sub))
grid2op.Exceptions.PlotExceptions.PlotError: Grid2OpException PlotError "You provided a layout with 0 elements while there are 14 substations on the powergrid. Your layout is invalid"127.0.0.1 - - [22/May/2020 13:33:02] "
POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [22/May/2020 13:33:02] "POST /_dash-update-component HTTP/1.1" 500 -
```

Data used:
"rte_case14_realistic" environment
scenario 000 (the first one)
max_iter : 300
agents: DoNothing and TopologyGreedy

This can be reproduced with:
```
import os
import grid2op
from grid2op.Runner import Runner
from grid2op.Agent import DoNothingAgent, TopologyGreedy
import shutil

path_agents = 'agent_logs'
max_iter = 300
env = grid2op.make('rte_case14_realistic')

for agentClass, agentName in zip([DoNothingAgent, TopologyGreedy],
                                 ["DoNothingAgent", "TopologyGreedy"]):
    path_this_agent = os.path.join(path_agents, agentName)
    shutil.rmtree(os.path.abspath(path_this_agent), ignore_errors=True)
    runner = Runner(**env.get_params_for_runner(),
                    agentClass=agentClass
                    )
    res = runner.run(path_save=path_this_agent, nb_episode=1, 
                     max_iter=max_iter)
    print("The results for the {} agent are:".format(agentName))
    for _, chron_id, cum_reward, nb_time_step, max_ts in res:
        msg_tmp = "\tFor chronics with id {}\n".format(chron_id)
        msg_tmp += "\t\t - cumulative reward: {:.6f}\n".format(cum_reward)
        msg_tmp += "\t\t - number of time steps completed: {:.0f} / {:.0f}".format(nb_time_step, max_ts)
        print(msg_tmp)
```

grid2op version: 0.9.1.post1

System specifications:
System edition: Windows 10 Family
System version: 18362.836
Processor: Intel(R) Core(TM) i7-6700HQ CPU @2.60GHz 2.59GHz
RAM memory: 16,0 Go
Product ID: 00325-95800-00000-AAOEM
System type: 64 bits operating system, x64 processor

**Comment by vinault** [comment]
Hi @Ashargin,

Thank you for reporting this bug. I was able to reproduce it.

**Comment by vinault** [comment]
Hi again, 

for some obscur reason, I cannot reproduce this error anymore...
I'll let you know when the new release is available so that you cannot try and reproduce it with the updated version.

**Comment by marota** [comment]
@Ashargin can you reproduce your test case with latest version of grid2viz go check if the bug is still there ?

**Comment by Ashargin** [comment]
After reinstalling Grid2Viz, I can confirm that I do not experience this issue anymore on Windows.

It looks good to me.
