### ISSUE TITLE
Reading data trouble

### ISSUE THREAD

**Issue by ID109** [mjothy/grid2viz#19]
C:\Users\Ivana>grid2viz --agents_path=Desktop\path_agents
Using default environment at c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\grid2viz\data\env_conf
the config file used is located at: c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\grid2viz\config.ini
Agents data used is located at: C:\Users\Ivana\Desktop\path_agents
Environment used is located at: c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\grid2viz\data\env_conf
 * Serving Flask app "grid2viz.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [02/Jun/2020 11:20:51] "GET /episodes HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2020 11:20:52] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2020 11:20:52] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2020 11:20:52] "GET /_favicon.ico?v=1.12.0 HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2020 11:20:52] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2020 11:20:52] "POST /_dash-update-component HTTP/1.1" 200 -
computing df
Environment
  0%|                                                                           | 0/30 [00:00<?, ?it/s]
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\dash\dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\dash\dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\grid2viz\src\episodes\episodes_clbk.py", line 34, in load_scenario_cards
    best_agent_episode = make_episode(best_agents[scenario]['agent'], scenario)
  File "c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\grid2viz\src\manager.py", line 49, in make_episode
    episode = compute_episode(episode_name, agent)
  File "c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\grid2viz\src\manager.py", line 90, in compute_episode
    episode_analytics = EpisodeAnalytics(episode_data, episode_name, agent)
  File "c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\grid2viz\src\kpi\EpisodeAnalytics.py", line 24, in __init__
    self.load, self.production, self.rho, self.action_data_table, self.computed_reward, self.flow_and_voltage_line = self._make_df_from_data(episode_data)
  File "c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\grid2viz\src\kpi\EpisodeAnalytics.py", line 103, in _make_df_from_data
    time_stamp = self.timestamp(obs)
  File "c:\users\ivana\appdata\local\programs\python\python38-32\lib\site-packages\grid2viz\src\kpi\EpisodeAnalytics.py", line 42, in timestamp
    return dt.datetime(obs.year[0], obs.month[0], obs.day[0], obs.hour_of_day[0],
IndexError: invalid index to scalar variable.

**Comment by vinault** [comment]
Hi @ID109, 
thank you for spotting this dependency problem. Commit 1485ba31c573f15f790d4b6c0fc1b5fd7a70830e should fix this. It's on bug-fix-v0.0.1 and will soon be merged on master.
