### ISSUE TITLE
Bug: non-empty timesteps list in agent overview when changing scenarios

### ISSUE THREAD

**Issue by marota** [mjothy/grid2viz#28]
After studying a scenario and some timesteps, the list of selected timesteps in agent overview remains non empty when switching scenario. With this new scenario with different dates (during which the previously selected timesteps do not exist), if not careful to empty manually the list, it will create a bug when going to agent study
![image](https://user-images.githubusercontent.com/5496312/87049858-c12c1600-c1fd-11ea-90dd-f4b90fe2124b.png)
On this example, 8 and 9 of April do not exist for this new scenario in April

**Comment by vinault** [comment]
For memory. This is not a particularly straightforward subject as we'd probably like to reset the timestamps list when opening a new scenario. 
The problem : one callback has for output this table in the agent overview view so that we cannot add a callback with this output in the scenario selection view. 
To be investigated...

**Comment by vinault** [comment]
To be tested : accessibility of Agent Study view when a selected timestep is outside of the scope of the studied agent.

**Comment by vinault** [comment]
With respect to the previous comment, an error is indeed thrown when the selected timestep is outside of the studied agent's scope.
The list of timesteps should be automatically filtered on the studied agent's scope.

```
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\Projects\RTE-Grid2Viz\grid2viz\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Projects\RTE-Grid2Viz\grid2viz\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Projects\RTE-Grid2Viz\grid2viz\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Projects\RTE-Grid2Viz\grid2viz\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Projects\RTE-Grid2Viz\grid2viz\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Projects\RTE-Grid2Viz\grid2viz\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Projects\RTE-Grid2Viz\grid2viz\venv\lib\site-packages\dash\dash.py", line 1031, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "D:\Projects\RTE-Grid2Viz\grid2viz\venv\lib\site-packages\dash\dash.py", line 966, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "D:\Projects\RTE-Grid2Viz\grid2viz\grid2viz\app.py", line 156, in register_page_lyt
    return micro.layout(user_selected_timestamp, study_agent, ref_agent, scenario), "micro", False, False, False, True
  File "D:\Projects\RTE-Grid2Viz\grid2viz\grid2viz\src\micro\micro_lyt.py", line 256, in layout
    center_indx = center_index(user_selected_timestamp, new_episode)
  File "D:\Projects\RTE-Grid2Viz\grid2viz\grid2viz\src\micro\micro_lyt.py", line 219, in center_index
    user_selected_timestamp, '%Y-%m-%d %H:%M')
ValueError: datetime.datetime(2019, 1, 8, 14, 25) is not in list
```
